log-level: debug
mixed-port: 7890
allow-lan: true
external-controller: 127.0.0.1:9090
unified-delay: true
tcp-concurrent: true
find-process-mode: strict
global-client-fingerprint: chrome
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  strict-route: true
dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
  nameserver-policy:
    geosite:cn,private:
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - AUTO
  - name: AUTO
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
  - name: AI
    type: select
    proxies:
rules:
  - RULE-SET,reject-list,REJECT
  - RULE-SET,ai,AI
  - DST-PORT,23301/22101-22102/20501/21601-21606,DIRECT
  - DOMAIN-SUFFIX,public-operation-hkrpg-sg.hoyoverse.com,DIRECT
  - DOMAIN-SUFFIX,public-operation-hk4e-sg.hoyoverse.com,DIRECT
  - DOMAIN-SUFFIX,public-operation-nap-sg.hoyoverse.com,DIRECT
  - DOMAIN-KEYWORD,hoyoverse.com,PROXY
  - DOMAIN-SUFFIX,ushd.xmsl.org,DIRECT
  - DOMAIN-SUFFIX,cf.gtlx.org,DIRECT
  - GEOSITE,GOOGLEFCM,DIRECT
  - GEOSITE,PRIVATE,DIRECT
  - GEOSITE,CN,DIRECT
  - GEOIP,PRIVATE,DIRECT,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
rule-providers:
  ai:
    type: http
    behavior: classical
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/ai.txt
    path: ./sukkaw_ruleset/ai.txt
  reject-list:
    type: http
    behavior: domain
    format: text
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/reject-list.txt
    path: ./v2ray-rules-da/reject-list.txt